/* Importing all the files in the directory. */
require("../css/style.css")
require("./navbar.js")
require("./Entry-form.js")
require("./address-form.js")
require("./documentUpload.js")
require("./lenders-table")
require("./fair-rates-result")
require("./final-form-check.js")
require("./get-started")
require("./calender-picker")
require("./tailwind.config.js")